{{- if .Values.jobs.generateAnalytics.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "dhis2-core-helm.fullname" . }}-generate-analytics"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"

spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: {{ include "dhis2-core-helm.fullname" . }}-generate-analytics-job
          image: curlimages/curl:latest
          env:
            - name: SERVICE_URL
              value: "http://{{ include "dhis2-core-helm.fullname" . }}:{{ .Values.service.port }}{{ .Values.ingress.path }}"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "dhis2-core-helm.fullname" . }}
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dhis2-core-helm.fullname" . }}
                  key: PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              {{- .Files.Get "scripts/generate-analytics.sh" | nindent 15 }}
      restartPolicy: OnFailure
{{- end }}

---

{{- if .Values.jobs.enableUsers.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "dhis2-core-helm.fullname" . }}-enable-user"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: {{ include "dhis2-core-helm.fullname" . }}-enable-user-job
          image: alpine/k8s:1.29.0
          env:
            - name: SERVICE_URL
              value: "http://{{ include "dhis2-core-helm.fullname" . }}:{{ .Values.service.port }}{{ .Values.ingress.path }}"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "dhis2-core-helm.fullname" . }}
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dhis2-core-helm.fullname" . }}
                  key: PASSWORD
            - name: TARGET_USER
              value: {{ .Values.jobs.enableUsers.targetUser }}
          command:
            - /bin/sh
            - -c
            - |
              {{- .Files.Get "scripts/enable-users.sh" | nindent 15 }}
      restartPolicy: OnFailure
{{- end }}

---

{{- if .Values.jobs.createMetricsUser.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "dhis2-core-helm.fullname" . }}-create-metrics-user"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "argocd.argoproj.io/sync-wave": "1"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: {{ include "dhis2-core-helm.fullname" . }}-create-metrics-user-job
          image: alpine/k8s:1.29.0
          env:
            - name: SERVICE_URL
              value: "http://{{ include "dhis2-core-helm.fullname" . }}:{{ .Values.service.port }}"
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: blsq-dhis2-metrics-admin-secret
                  key: initial-username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blsq-dhis2-metrics-admin-secret
                  key: initial-password
            - name: METRICS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: blsq-dhis2-metrics-admin-secret
                  key: username
            - name: METRICS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blsq-dhis2-metrics-admin-secret
                  key: password
            {{- with .Values.jobs.createMetricsUser.userRoleIds }}
            - name: USER_ROLE_IDS
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.jobs.createMetricsUser.orgUnitIds }}
            - name: ORG_UNIT_IDS
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.jobs.createMetricsUser.firstName }}
            - name: METRICS_FIRST_NAME
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.jobs.createMetricsUser.surname }}
            - name: METRICS_SURNAME
              value: {{ . | quote }}
            {{- end }}
          command:
            - /bin/sh
            - -c
            - |
              {{- .Files.Get "scripts/create-metrics-user.sh" | nindent 15 }}
      restartPolicy: OnFailure
{{- end }}

---

{{- if .Values.jobs.installApps.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "dhis2-core-helm.fullname" . }}-install-apps"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"

spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: {{ include "dhis2-core-helm.fullname" . }}-install-apps-job
          image: alpine/k8s:1.29.0
          env:
            - name: SERVICE_URL
              value: "http://{{ include "dhis2-core-helm.fullname" . }}:{{ .Values.service.port }}{{ .Values.ingress.path }}"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "dhis2-core-helm.fullname" . }}
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dhis2-core-helm.fullname" . }}
                  key: PASSWORD
            - name: APPS
              value: {{ .Values.jobs.installApps.apps | toJson | quote }}
          command:
            - /bin/sh
            - -c
            - |
              {{- .Files.Get "scripts/install-apps.sh" | nindent 15 }}
      restartPolicy: OnFailure
{{- end }}
